[book]
authors = ["Erick Adriano Sebastian"]
language = "id"
src = "src"
title = "MELISA — Dokumentasi Resmi"
description = "Management Environment Linux Sandbox — Panduan Lengkap Bahasa Indonesia"
 
[build]
build-dir = "book"
create-missing = true
 
[output.html]
theme = "theme"
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ernoba/melisa_core"
git-repository-icon = "fa-github"
no-section-label = false
additional-css = ["theme/custom.css"]

[output.html.variables]
# Tambahkan baris ini agar template mengenali variabel 'github'
github = "https://github.com/ernoba/melisa_core"
