// ============================================================================
// src/core/container/network.rs
//
// Network configuration management for LXC containers.
// LXC container network configuration:
//   - Inject veth network config into the LXC config file.
//   - Write and lock a container-local resolv.conf.
//   - Unlock (remove chattr +i) on cleanup.
//   - Manage host-shared folder bind-mounts.
//   - Re-initialize host-level network infrastructure (lxc-net, firewall).
// ============================================================================

use std::process::Stdio;
use tokio::fs::{self, OpenOptions};
use tokio::io::AsyncWriteExt;
use tokio::process::Command;
use std::path::Path;
use indicatif::ProgressBar;

use crate::cli::color::{GREEN, RED, RESET, YELLOW};
use crate::core::container::types::LXC_BASE_PATH;
use crate::distros::host_distro::{detect_host_distro, get_distro_config, FirewallKind};

// ── Network configuration injection ─────────────────────────────────────────

/// Appends a veth network stanza to the container's LXC config file.
///
/// A randomly generated MAC address is used so that containers obtain
/// unique DHCP leases on the `lxcbr0` bridge.
///
/// Skips injection if the config already contains `lxc.net.0.link`.
///
/// # Arguments
/// * `name` - Container name.
/// * `pb`   - Progress bar for inline status messages.
pub async fn inject_network_config(name: &str, pb: &ProgressBar) {
    let config_path = format!("{}/{}/config", LXC_BASE_PATH, name);

    if !Path::new(&config_path).exists() {
        pb.println(format!(
            "{}[WARNING]{} LXC config file not found at '{}'. Skipping network injection.",
            YELLOW, RESET, config_path
        ));
        return;
    }

    let existing_content = fs::read_to_string(&config_path).await.unwrap_or_default();
    if existing_content.contains("lxc.net.0.link") {
        pb.println(format!(
            "{}[SKIP]{} Network configuration already present. Skipping injection.",
            YELLOW, RESET
        ));
        return;
    }

    let mac_byte_a = rand::random::<u8>();
    let mac_byte_b = rand::random::<u8>();

    let network_stanza = format!(
        "\n# Auto-generated by MELISA\n\
        lxc.net.0.type = veth\n\
        lxc.net.0.link = lxcbr0\n\
        lxc.net.0.flags = up\n\
        lxc.net.0.hwaddr = ee:ec:fa:5e:{:02x}:{:02x}\n",
        mac_byte_a, mac_byte_b
    );

    match OpenOptions::new().append(true).open(&config_path).await {
        Ok(mut file) => {
            if let Err(err) = file.write_all(network_stanza.as_bytes()).await {
                eprintln!(
                    "{}[ERROR]{} Failed to write network configuration: {}",
                    RED, RESET, err
                );
            }
        }
        Err(err) => {
            eprintln!(
                "{}[ERROR]{} Failed to open LXC config file '{}': {}",
                RED, RESET, config_path, err
            );
        }
    }
}

// ── DNS configuration ────────────────────────────────────────────────────────

/// Writes a locked `resolv.conf` inside the container's rootfs.
///
/// Uses Google's public DNS servers (8.8.8.8 / 8.8.4.4) and applies
/// `chattr +i` to prevent the container from overwriting them.
///
/// # Arguments
/// * `name` - Container name.
/// * `pb`   - Progress bar for inline status messages.
pub async fn setup_container_dns(name: &str, pb: &ProgressBar) {
    let etc_path = format!("{}/{}/rootfs/etc", LXC_BASE_PATH, name);
    let dns_path = format!("{}/resolv.conf", etc_path);

    // Ensure the /etc directory exists inside the rootfs.
    let _ = Command::new("sudo")
        .args(&["mkdir", "-p", &etc_path])
        .status()
        .await;

    // Remove any existing resolv.conf (may be immutable from a previous setup).
    let _ = Command::new("sudo")
        .args(&["chattr", "-i", &dns_path])
        .status()
        .await;
    let _ = Command::new("sudo")
        .args(&["rm", "-f", &dns_path])
        .status()
        .await;

    let dns_content = "nameserver 8.8.8.8\\nnameserver 8.8.4.4\\n";
    let write_status = Command::new("sudo")
        .args(&[
            "bash", "-c",
            &format!("echo -e '{}' > {}", dns_content, dns_path),
        ])
        .status()
        .await;

    match write_status {
        Ok(s) if s.success() => {
            let lock_status = Command::new("sudo")
                .args(&["chattr", "+i", &dns_path])
                .status()
                .await;

            match lock_status {
                Ok(ls) if ls.success() => {
                    pb.println(format!(
                        "{}[INFO]{} DNS configured and locked successfully.",
                        GREEN, RESET
                    ));
                }
                _ => {
                    pb.println(format!(
                        "{}[WARNING]{} DNS written but failed to apply immutable lock (chattr).",
                        YELLOW, RESET
                    ));
                }
            }
        }
        _ => {
            eprintln!("{}[ERROR]{} Failed to configure DNS for container '{}'.", RED, RESET, name);
        }
    }
}

/// Removes the immutable lock from a container's `resolv.conf`.
///
/// Called before container deletion to allow `lxc-destroy` to remove files.
///
/// # Arguments
/// * `name` - Container name.
pub async fn unlock_container_dns(name: &str) {
    let dns_path = format!("{}/{}/rootfs/etc/resolv.conf", LXC_BASE_PATH, name);
    let _ = Command::new("sudo")
        .args(&["-n", "chattr", "-i", &dns_path])
        .status()
        .await;
}

// ── Shared folder management ─────────────────────────────────────────────────

/// Mounts a host directory into the container via LXC bind-mount configuration.
///
/// Appends the mount entry to the container's config file and applies
/// `100000:100000` ownership to the host path for unprivileged containers.
///
/// # Arguments
/// * `container_name`  - Target container name.
/// * `host_path`       - Absolute path on the host.
/// * `container_path`  - Absolute path inside the container rootfs.
pub async fn add_shared_folder(container_name: &str, host_path: &str, container_path: &str) {
    let config_path = format!("{}/{}/config", LXC_BASE_PATH, container_name);
    let bind_entry = format!(
        "lxc.mount.entry = {} {} none bind,create=dir 0 0\n",
        host_path, container_path
    );

    // Apply unprivileged UID/GID mapping to the host directory.
    let chown_status = Command::new("sudo")
        .args(&["chown", "-R", "100000:100000", host_path])
        .status()
        .await;

    match chown_status {
        Ok(s) if s.success() => {
            println!(
                "{}[INFO]{} Ownership of '{}' mapped to 100000:100000.",
                crate::cli::color::BOLD, RESET, host_path
            );
        }
        _ => {
            eprintln!(
                "{}[WARNING]{} Failed to remap ownership of '{}'. \
                The shared folder may not be accessible inside the container.",
                YELLOW, RESET, host_path
            );
        }
    }

    // Append the bind-mount entry to the LXC config.
    match OpenOptions::new().append(true).open(&config_path).await {
        Ok(mut file) => {
            if let Err(err) = file.write_all(bind_entry.as_bytes()).await {
                eprintln!(
                    "{}[ERROR]{} Failed to write bind-mount entry: {}",
                    RED, RESET, err
                );
            } else {
                println!(
                    "{}[SUCCESS]{} Shared folder '{}' → '{}' configured.",
                    GREEN, RESET, host_path, container_path
                );
            }
        }
        Err(err) => {
            eprintln!(
                "{}[ERROR]{} Failed to open LXC config file '{}': {}",
                RED, RESET, config_path, err
            );
        }
    }
}

/// Removes a bind-mount entry from the container's LXC config file.
///
/// # Arguments
/// * `container_name`  - Target container name.
/// * `host_path`       - Absolute path on the host (used to identify the entry).
/// * `container_path`  - Absolute path inside the container (used to identify the entry).
pub async fn remove_shared_folder(container_name: &str, host_path: &str, container_path: &str) {
    let config_path = format!("{}/{}/config", LXC_BASE_PATH, container_name);
    let target_entry = format!(
        "lxc.mount.entry = {} {} none bind,create=dir 0 0",
        host_path, container_path
    );

    match fs::read_to_string(&config_path).await {
        Ok(content) => {
            let updated_content: String = content
                .lines()
                .filter(|line| !line.trim().eq(target_entry.trim()))
                .map(|line| format!("{}\n", line))
                .collect();

            if let Err(err) = fs::write(&config_path, updated_content).await {
                eprintln!(
                    "{}[ERROR]{} Failed to update LXC config file: {}",
                    RED, RESET, err
                );
            } else {
                println!(
                    "{}[SUCCESS]{} Shared folder '{}' → '{}' removed from config.",
                    GREEN, RESET, host_path, container_path
                );
            }
        }
        Err(err) => {
            eprintln!(
                "{}[ERROR]{} Cannot read LXC config file '{}': {}",
                RED, RESET, config_path, err
            );
        }
    }
}

// ── Host network infrastructure ──────────────────────────────────────────────

/// Re-initializes the host-level network infrastructure required by LXC.
///
/// Starts `lxc-net` and configures the active firewall to allow traffic
/// through the `lxcbr0` bridge.
///
/// # Arguments
/// * `audit` - When `true`, subprocess output is forwarded to the terminal.
pub async fn ensure_host_network_ready(audit: bool) {
    println!(
        "{}[INFO]{} Re-initializing host network infrastructure…",
        crate::cli::color::BOLD, RESET
    );

    let lxc_net_args = &["-n", "systemctl", "start", "lxc-net"];
    if audit {
        let _ = Command::new("sudo")
            .args(lxc_net_args)
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await;
    } else {
        let _ = Command::new("sudo").args(lxc_net_args).status().await;
    }

    let host_distro = detect_host_distro().await;
    let distro_config = get_distro_config(&host_distro);

    configure_firewall_for_lxc(&distro_config.firewall_tool).await;
}

/// Applies firewall rules to allow LXC bridge traffic.
async fn configure_firewall_for_lxc(firewall: &FirewallKind) {
    match firewall {
        FirewallKind::Firewalld => {
            let _ = Command::new("sudo")
                .args(&[
                    "-n", "firewall-cmd",
                    "--zone=trusted",
                    "--add-interface=lxcbr0",
                    "--permanent",
                ])
                .status()
                .await;
            let _ = Command::new("sudo")
                .args(&["-n", "firewall-cmd", "--reload"])
                .status()
                .await;
        }
        FirewallKind::Ufw => {
            let _ = Command::new("sudo")
                .args(&["-n", "ufw", "allow", "in", "on", "lxcbr0"])
                .status()
                .await;
            let _ = Command::new("sudo")
                .args(&["-n", "ufw", "reload"])
                .status()
                .await;
        }
        FirewallKind::Iptables => {
            let _ = Command::new("sudo")
                .args(&["-n", "iptables", "-I", "INPUT", "-i", "lxcbr0", "-j", "ACCEPT"])
                .status()
                .await;
        }
    }
}

// ============================================================================
// Unit Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Verifies the bind-mount entry format matches LXC expectations.
    #[test]
    fn test_bind_mount_entry_format_is_correct() {
        let host_path = "/home/user/project";
        let container_path = "/app";
        let expected = format!(
            "lxc.mount.entry = {} {} none bind,create=dir 0 0\n",
            host_path, container_path
        );
        assert!(
            expected.starts_with("lxc.mount.entry = "),
            "Bind-mount entry must begin with 'lxc.mount.entry = '"
        );
        assert!(
            expected.contains("none bind,create=dir 0 0"),
            "Bind-mount entry must contain the bind options"
        );
    }

    /// Verifies the DNS content string uses the correct format.
    #[test]
    fn test_dns_content_contains_google_nameservers() {
        let dns_content = "nameserver 8.8.8.8\\nnameserver 8.8.4.4\\n";
        assert!(
            dns_content.contains("8.8.8.8"),
            "DNS config must include Google primary nameserver"
        );
        assert!(
            dns_content.contains("8.8.4.4"),
            "DNS config must include Google secondary nameserver"
        );
    }

    /// Verifies the network stanza template includes required LXC keys.
    #[test]
    fn test_network_stanza_contains_required_lxc_keys() {
        let stanza = format!(
            "\n# Auto-generated by MELISA\n\
            lxc.net.0.type = veth\n\
            lxc.net.0.link = lxcbr0\n\
            lxc.net.0.flags = up\n\
            lxc.net.0.hwaddr = ee:ec:fa:5e:{:02x}:{:02x}\n",
            0xAB_u8, 0xCD_u8
        );
        assert!(stanza.contains("lxc.net.0.type = veth"), "Must configure veth network type");
        assert!(stanza.contains("lxc.net.0.link = lxcbr0"), "Must link to lxcbr0 bridge");
        assert!(stanza.contains("lxc.net.0.flags = up"), "Must set interface flags to up");
        assert!(stanza.contains("lxc.net.0.hwaddr"), "Must include a MAC address");
    }

    /// Verifies remove_shared_folder filters the correct line from a multi-line config.
    #[test]
    fn test_bind_entry_removal_logic() {
        let host_path = "/host/data";
        let container_path = "/container/data";
        let target_entry = format!(
            "lxc.mount.entry = {} {} none bind,create=dir 0 0",
            host_path, container_path
        );
        let config_content = format!(
            "lxc.utsname = mybox\n{}\nlxc.net.0.type = veth\n",
            target_entry
        );

        let filtered: String = config_content
            .lines()
            .filter(|line| !line.trim().eq(target_entry.trim()))
            .map(|line| format!("{}\n", line))
            .collect();

        assert!(
            !filtered.contains(&target_entry),
            "Filtered config must not contain the removed bind-mount entry"
        );
        assert!(
            filtered.contains("lxc.utsname = mybox"),
            "Filtered config must retain unrelated entries"
        );
    }
}